export const ALL_POKEMON_REQUEST = "ALL_POKEMON_REQUEST";
export const ALL_POKEMON_SUCCESS = "ALL_POKEMON_SUCCESS";
export const ALL_POKEMON_FAIL = "ALL_POKEMON_FAIL";

export const NEW_POKEMON_REQUEST = "NEW_POKEMON_REQUEST";
export const NEW_POKEMON_SUCCESS = "NEW_POKEMON_SUCCESS";
export const NEW_POKEMON_RESET = "NEW_POKEMON_RESET";
export const NEW_POKEMON_FAIL = "NEW_POKEMON_FAIL";

export const DELETE_POKEMON_REQUEST = "DELETE_POKEMON_REQUEST";
export const DELETE_POKEMON_SUCCESS = "DELETE_POKEMON_SUCCESS";
export const DELETE_POKEMON_RESET = "DELETE_POKEMON_RESET";
export const DELETE_POKEMON_FAIL = "DELETE_POKEMON_FAIL";

export const POKEMON_DETAILS_REQUEST = "POKEMON_DETAILS_REQUEST";
export const POKEMON_DETAILS_SUCCESS = "POKEMON_DETAILS_SUCCESS";
export const POKEMON_DETAILS_FAIL = "POKEMON_DETAILS_FAIL";

export const POKEMON_FEED_REQUEST = "POKEMON_FEED_REQUEST";
export const POKEMON_FEED_SUCCESS = "POKEMON_FEED_SUCCESS";
export const POKEMON_FEED_FAIL = "POKEMON_FEED_FAIL";
export const POKEMON_FEED_RESET = "POKEMON_FEED_RESET";

export const MY_POKEMON_REQUEST = "MY_POKEMON_REQUEST";
export const MY_POKEMON_SUCCESS = "MY_POKEMON_SUCCESS";
export const MY_POKEMON_FAIL = "MY_POKEMON_FAIL";

export const ADOPT_POKEMON_REQUEST = "ADOPT_POKEMON_REQUEST";
export const ADOPT_POKEMON_SUCCESS = "ADOPT_POKEMON_SUCCESS";
export const ADOPT_POKEMON_FAIL = "ADOPT_POKEMON_FAIL";
export const ADOPT_POKEMON_RESET = "ADOPT_POKEMON_RESET";

export const REMOVE_POKEMON_REQUEST = "REMOVE_POKEMON_REQUEST";
export const REMOVE_POKEMON_SUCCESS = "REMOVE_POKEMON_SUCCESS";
export const REMOVE_POKEMON_FAIL = "REMOVE_POKEMON_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
